<?php

namespace Database\Seeders;

use App\Models\ApplicantEducation;
use App\Models\ApplicantFamily;
use App\Models\ApplicantHealthEmergency;
use App\Models\ApplicantSibling;
use App\Models\Application;
use Illuminate\Database\Seeder;

class ApplicationSeeder extends Seeder
{
    public function run(): void
    {
        $applicants = [
            [
                'application_no' => 'APP-2026-0001',
                'first_name' => 'Maria Clara',
                'last_name' => 'Santos',
                'middle_name' => 'De los Santos',
                'lrn' => '123456789012',
                'campus_id' => 1,
                'course_1_id' => 3,
                'course_2_id' => 1,
                'student_type' => 'Freshman',
                'status' => 'Approved for Exam',
                'date_of_birth' => '2007-05-12',
                'age' => 18,
                'sex' => 'Female',
                'civil_status' => 'Single',
                'place_of_birth' => 'Pili, Camarines Sur',
                'religion' => 'Roman Catholic',
                'nationality' => 'Filipino',
                'present_address' => 'San Agustin, Pili, Camarines Sur',
                'permanent_address' => 'San Agustin, Pili, Camarines Sur',
                'mobile_number' => '09171234567',
                'email_address' => 'maria.santos@gmail.com',
            ],
            [
                'application_no' => 'APP-2026-0002',
                'first_name' => 'Gabriel',
                'last_name' => 'Alvarez',
                'middle_name' => 'Bautista',
                'lrn' => '987654321098',
                'campus_id' => 1,
                'course_1_id' => 1,
                'course_2_id' => 2,
                'student_type' => 'Freshman',
                'status' => 'Pending',
                'date_of_birth' => '2007-10-22',
                'age' => 18,
                'sex' => 'Male',
                'civil_status' => 'Single',
                'place_of_birth' => 'Iriga City',
                'religion' => 'Protestant',
                'nationality' => 'Filipino',
                'present_address' => 'San Agustin, Iriga City, Camarines Sur',
                'permanent_address' => 'San Agustin, Iriga City, Camarines Sur',
                'mobile_number' => '09187654321',
                'email_address' => 'gabriel.alvarez@yahoo.com',
            ],
            [
                'application_no' => 'APP-2026-0003',
                'first_name' => 'Christine Joy',
                'last_name' => 'Bello',
                'middle_name' => 'Cruz',
                'lrn' => '555111222333',
                'campus_id' => 2,
                'course_1_id' => 2,
                'course_2_id' => 3,
                'student_type' => 'Freshman',
                'status' => 'Approved for Exam',
                'date_of_birth' => '2007-02-14',
                'age' => 18,
                'sex' => 'Female',
                'civil_status' => 'Single',
                'place_of_birth' => 'Calabanga, Camarines Sur',
                'religion' => 'Roman Catholic',
                'nationality' => 'Filipino',
                'present_address' => 'Poblacion, Calabanga, Camarines Sur',
                'permanent_address' => 'Poblacion, Calabanga, Camarines Sur',
                'mobile_number' => '09201112233',
                'email_address' => 'cj.bello@gmail.com',
            ],
            [
                'application_no' => 'APP-2026-0004',
                'first_name' => 'Ramon',
                'last_name' => 'Olaso',
                'middle_name' => 'Ramos',
                'lrn' => '888999000111',
                'campus_id' => 1,
                'course_1_id' => 6,
                'course_2_id' => 5,
                'student_type' => 'Freshman',
                'status' => 'Scheduled',
                'exam_schedule_id' => 1,
                'date_of_birth' => '2006-11-30',
                'age' => 19,
                'sex' => 'Male',
                'civil_status' => 'Single',
                'place_of_birth' => 'Naga City',
                'religion' => 'Roman Catholic',
                'nationality' => 'Filipino',
                'present_address' => 'Concepcion Pequeña, Naga City',
                'permanent_address' => 'Concepcion Pequeña, Naga City',
                'mobile_number' => '09289990001',
                'email_address' => 'ramon.olaso@gmail.com',
            ],
            [
                'application_no' => 'APP-2026-0005',
                'first_name' => 'Juan',
                'last_name' => 'Dela Cruz',
                'middle_name' => 'Perez',
                'lrn' => '102938475612',
                'campus_id' => 1,
                'course_1_id' => 4,
                'course_2_id' => 3,
                'student_type' => 'Freshman',
                'status' => 'Pending',
                'date_of_birth' => '2007-08-19',
                'age' => 18,
                'sex' => 'Male',
                'civil_status' => 'Single',
                'place_of_birth' => 'Pili, Camarines Sur',
                'religion' => 'Roman Catholic',
                'nationality' => 'Filipino',
                'present_address' => 'Cadlan, Pili, Camarines Sur',
                'permanent_address' => 'Cadlan, Pili, Camarines Sur',
                'mobile_number' => '09193334455',
                'email_address' => 'juan.delacruz@gmail.com',
            ],
            [
                'application_no' => 'APP-2026-0006',
                'first_name' => 'Ana Marie',
                'last_name' => 'Villanueva',
                'middle_name' => 'Flores',
                'lrn' => '444555666777',
                'campus_id' => 1,
                'course_1_id' => 5,
                'course_2_id' => 7,
                'student_type' => 'Freshman',
                'status' => 'Rejected',
                'rejection_reason' => 'Incomplete Form 138 / Blurred Senior High GWA record',
                'date_of_birth' => '2007-01-05',
                'age' => 18,
                'sex' => 'Female',
                'civil_status' => 'Single',
                'place_of_birth' => 'Bula, Camarines Sur',
                'religion' => 'Roman Catholic',
                'nationality' => 'Filipino',
                'present_address' => 'Fabrica, Bula, Camarines Sur',
                'permanent_address' => 'Fabrica, Bula, Camarines Sur',
                'mobile_number' => '09176667788',
                'email_address' => 'ana.villanueva@yahoo.com',
            ],
            [
                'application_no' => 'APP-2026-0007',
                'first_name' => 'Kenneth',
                'last_name' => 'Morales',
                'middle_name' => 'Tan',
                'lrn' => '333222111444',
                'campus_id' => 1,
                'course_1_id' => 7,
                'course_2_id' => 8,
                'student_type' => 'Freshman',
                'status' => 'Approved for Exam',
                'date_of_birth' => '2007-04-18',
                'age' => 18,
                'sex' => 'Male',
                'civil_status' => 'Single',
                'place_of_birth' => 'Baao, Camarines Sur',
                'religion' => 'Roman Catholic',
                'nationality' => 'Filipino',
                'present_address' => 'San Nicolas, Baao, Camarines Sur',
                'permanent_address' => 'San Nicolas, Baao, Camarines Sur',
                'mobile_number' => '09214445566',
                'email_address' => 'kenneth.morales@gmail.com',
            ],
            [
                'application_no' => 'APP-2026-0008',
                'first_name' => 'Jessica',
                'last_name' => 'Alcantara',
                'middle_name' => 'Rios',
                'lrn' => '777888999000',
                'campus_id' => 1,
                'course_1_id' => 8,
                'course_2_id' => 9,
                'student_type' => 'Transferee',
                'status' => 'Pending',
                'date_of_birth' => '2005-09-15',
                'age' => 20,
                'sex' => 'Female',
                'civil_status' => 'Single',
                'place_of_birth' => 'Naga City',
                'religion' => 'Iglesia ni Cristo',
                'nationality' => 'Filipino',
                'present_address' => 'Triangulo, Naga City',
                'permanent_address' => 'Triangulo, Naga City',
                'mobile_number' => '09395556677',
                'email_address' => 'jessica.alcantara@gmail.com',
            ],
            [
                'application_no' => 'APP-2026-0009',
                'first_name' => 'Christian',
                'last_name' => 'Navarro',
                'middle_name' => 'Diaz',
                'lrn' => '121212121212',
                'campus_id' => 1,
                'course_1_id' => 9,
                'course_2_id' => 10,
                'student_type' => 'Freshman',
                'status' => 'Approved for Exam',
                'date_of_birth' => '2007-06-25',
                'age' => 18,
                'sex' => 'Male',
                'civil_status' => 'Single',
                'place_of_birth' => 'Minalabac, Camarines Sur',
                'religion' => 'Roman Catholic',
                'nationality' => 'Filipino',
                'present_address' => 'San Jose, Minalabac, Camarines Sur',
                'permanent_address' => 'San Jose, Minalabac, Camarines Sur',
                'mobile_number' => '09181112233',
                'email_address' => 'christian.navarro@gmail.com',
            ],
            [
                'application_no' => 'APP-2026-0010',
                'first_name' => 'Bea Patricia',
                'last_name' => 'Solis',
                'middle_name' => 'Lim',
                'lrn' => '343434343434',
                'campus_id' => 1,
                'course_1_id' => 10,
                'course_2_id' => 1,
                'student_type' => 'Freshman',
                'status' => 'Pending',
                'date_of_birth' => '2007-12-01',
                'age' => 18,
                'sex' => 'Female',
                'civil_status' => 'Single',
                'place_of_birth' => 'Ocampo, Camarines Sur',
                'religion' => 'Roman Catholic',
                'nationality' => 'Filipino',
                'present_address' => 'Poblacion West, Ocampo, Camarines Sur',
                'permanent_address' => 'Poblacion West, Ocampo, Camarines Sur',
                'mobile_number' => '09278889900',
                'email_address' => 'bea.solis@gmail.com',
            ],
            [
                'application_no' => 'APP-2026-0011',
                'first_name' => 'Daniel',
                'last_name' => 'Padilla',
                'middle_name' => 'Ford',
                'lrn' => '565656565656',
                'campus_id' => 1,
                'course_1_id' => 3,
                'course_2_id' => 4,
                'student_type' => 'Second Courser',
                'status' => 'Scheduled',
                'exam_schedule_id' => 1,
                'date_of_birth' => '2004-03-20',
                'age' => 21,
                'sex' => 'Male',
                'civil_status' => 'Single',
                'place_of_birth' => 'Pili, Camarines Sur',
                'religion' => 'Roman Catholic',
                'nationality' => 'Filipino',
                'present_address' => 'Himaao, Pili, Camarines Sur',
                'permanent_address' => 'Himaao, Pili, Camarines Sur',
                'mobile_number' => '09172223344',
                'email_address' => 'daniel.padilla@gmail.com',
            ],
            [
                'application_no' => 'APP-2026-0012',
                'first_name' => 'Angelica',
                'last_name' => 'Panganiban',
                'middle_name' => 'David',
                'lrn' => '787878787878',
                'campus_id' => 1,
                'course_1_id' => 2,
                'course_2_id' => 5,
                'student_type' => 'Freshman',
                'status' => 'Rejected',
                'rejection_reason' => 'Discrepancy in LRN and PSA Birth Certificate details',
                'date_of_birth' => '2007-07-07',
                'age' => 18,
                'sex' => 'Female',
                'civil_status' => 'Single',
                'place_of_birth' => 'Pili, Camarines Sur',
                'religion' => 'Roman Catholic',
                'nationality' => 'Filipino',
                'present_address' => 'Palangue, Pili, Camarines Sur',
                'permanent_address' => 'Palangue, Pili, Camarines Sur',
                'mobile_number' => '09990001122',
                'email_address' => 'angelica.panganiban@gmail.com',
            ],
        ];

        $activeSchoolYear = \App\Models\SchoolYear::where('is_active', true)->first() ?? \App\Models\SchoolYear::first();
        $defaultExamSchedule = \App\Models\ExamSchedule::first();

        foreach ($applicants as $appData) {
            $appData['school_year_id'] = $appData['school_year_id'] ?? $activeSchoolYear?->id ?? 1;
            if (!empty($appData['exam_schedule_id'])) {
                $appData['exam_schedule_id'] = $defaultExamSchedule?->id ?? null;
            }
            $application = Application::updateOrCreate(
                ['application_no' => $appData['application_no']],
                $appData
            );

            ApplicantFamily::updateOrCreate(
                ['application_id' => $application->id],
                [
                    'father_name' => 'Nestor ' . $application->last_name,
                    'father_age' => 50,
                    'father_education' => 'High School Graduate',
                    'father_contact' => '09171112233',
                    'father_occupation' => 'Farmer',
                    'father_living_status' => 'Living',
                    'father_living_with_family' => 'Yes',
                    'mother_name' => 'Elena ' . $application->last_name,
                    'mother_age' => 48,
                    'mother_education' => 'College Graduate',
                    'mother_contact' => '09172223344',
                    'mother_occupation' => 'Housewife / Teacher',
                    'mother_living_status' => 'Living',
                    'mother_living_with_family' => 'Yes',
                    'family_monthly_income' => '15,000 - 25,000 PHP',
                    'housing_condition' => 'Owned',
                    'language_spoken' => 'Bikol, Tagalog, English',
                ]
            );

            ApplicantEducation::updateOrCreate(
                ['application_id' => $application->id],
                [
                    'elem_name' => 'Pili Central School',
                    'elem_grad_year' => '2019',
                    'elem_address' => 'Pili, Camarines Sur',
                    'jhs_name' => 'Pili National High School',
                    'jhs_grad_year' => '2023',
                    'jhs_address' => 'Pili, Camarines Sur',
                    'shs_name' => 'CBSUA Science High School',
                    'shs_grad_year' => '2025',
                    'shs_address' => 'San Jose, Pili, Camarines Sur',
                    'shs_track' => 'STEM',
                    'shs_avg_g11' => '92.5',
                    'shs_avg_g12' => '94.0',
                    'future_outlook' => 'Aspiring to become an agricultural leader and innovator.',
                ]
            );

            ApplicantHealthEmergency::updateOrCreate(
                ['application_id' => $application->id],
                [
                    'pwd_status' => false,
                    'hospitalized_status' => false,
                    'emergency_name' => 'Elena ' . $application->last_name,
                    'emergency_relation' => 'Mother',
                    'emergency_contact' => '09172223344',
                    'emergency_address' => $application->present_address,
                ]
            );
        }
    }
}
